include_recipe "hive2::metastore_db"
include_recipe "hive2::metastore_service"
include_recipe "hive2::cleaner"
include_recipe "hive2::tez"
include_recipe "hive2::server2"
include_recipe "hive2::llap"
